yolo_workspace_processing_node:
  ros__parameters:
    # ROS Teme
    yolo_detections_topic: "/yolo/detections"
    output_topic: "/workspace_detection_boxes"
    positions_topic: "/vision/object_positions"

    # --- NOVI INTRINZIČNI PARAMETRI (Iz tvoje rektificirane P matrice) ---
    fx: 721.29907
    fy: 716.27563
    cx: 344.87706
    cy: 292.58597

    # --- NOVI EKSTRINZIČNI PARAMETRI (Rotacija 3x3 u jednom redu) ---
    R_cam_to_robot: [
       0.99900,  0.02203, -0.03903,
       0.02640, -0.99298,  0.11528,
      -0.03621, -0.11619, -0.99257
    ]

    # Vektor translacije T (X, Y, Z) izražen direktno u milimetrima (m * 1000)
    t_cam_to_robot: [-221.58, -38.74, 622.54]
