yolo_workspace_processing_node:
  ros__parameters:
    # ROS Teme
    yolo_detections_topic: "/yolo/detections"
    output_topic: "/workspace_detection_boxes"
    positions_topic: "/vision/object_positions"

    # --- NOVI INTRINZIČNI PARAMETRI (Iz tvoje rektificirane P matrice) ---
    fx: 721.29907
    fy: 716.27563
    cx: 344.87706
    cy: 292.58597

    # --- NOVI EKSTRINZIČNI PARAMETRI (Rotacija 3x3 u jednom redu) ---
    R_cam_to_robot: [
       0.03047,-0.99869,-0.04116,
       -0.99088,-0.03559, 0.12996,
      -0.13126, 0.03682,-0.99066
    ]

    # Vektor translacije T (X, Y, Z) izražen direktno u milimetrima (m * 1000)
    t_cam_to_robot: [16.05, 177.88, 687.39]


